koel/koel

app/Services/Media.php

They probably aren't music files
Prevents
> Undefined index: playtime_seconds
while scanning

Ignore files that dont have a playtime

---

app/Console/Commands/Init.php
app/Console/Kernel.php

Totally not necessary, but if you're interested, this would allow you to simplify this:
To this:

Add an init command

---

app/Http/Controllers/API/Controller.php
app/Http/Controllers/API/PlaylistController.php
app/Http/Controllers/API/UserController.php
app/Http/Requests/API/UserUpdateRequest.php
app/Http/routes.php
app/Models/User.php
app/Policies/PlaylistPolicy.php
app/Policies/UserPolicy.php
app/Providers/AuthServiceProvider.php
app/Providers/RouteServiceProvider.php
tests/PlaylistTest.php
tests/UserTest.php

The comment below motivated me to find a better solution for the
repeated authorisation checks:
```php
// This can't be put into a Request authorize(), due to Laravel(?)'s limitation.
```
This is the result.

Use Laravel built-in authorization

---

app/Models/Song.php

This fixes the problem that Song.length is returned as string.
Sorry that I messed up #118 :(

Add cast to convert Song.length to float

---

resources/assets/js/app.vue

This allows the user to use the media keys on their keyboard if they have them. ex. Prev, Pause/Play, Next

Add support for Media keys on keyboard

---

resources/assets/js/app.vue
resources/assets/js/stores/queue.js
resources/assets/js/stores/song.js

I found some typos in the code comments.

Fixed several typos in comments

---

app/Console/Commands/SyncMedia.php

This makes more sense as all the other ouput handles plural this way in the file.

Change songs(s) to song(s)

---

app/Services/Media.php

filter by file extension (case insentitive) in order to get *.MP3 i.e.

case insensitive file extension lookup

---

resources/assets/js/components/shared/song-menu.vue

Since my previous PR caused selection issues, this adds the same navigation function to artist/album views via the right-click context menu instead.

Navigate via context menu

---

resources/assets/js/app.vue
resources/assets/js/components/shared/song-list.vue

Advanced subsort to support any number of sort keys in the event that 2 records are identical on one key (i.e., artist, then album, then track number within that album)

Advanced subsort

---

app/Models/File.php
resources/assets/js/components/shared/song-list.vue

Added multiple methods of attempting to retrieve the track for a file, added a default sort for song lists.

Fix - default sorting track parsing

---

resources/assets/sass/vendor/_plyr.scss

SASS ignores variables, defined in if-statement
http://stackoverflow.com/questions/15371332/sass-ignores-variables-defined-in-if-statement

app.scss compiled failed

---

resources/assets/js/components/site-footer/equalizer.vue
resources/assets/js/components/site-footer/index.vue
resources/assets/sass/partials/_vars.scss

First of all, thanks for this amazing project. I've been using Koel for a while now and I'd like to contribute something - this is a start, I've never played with SASS before and I've never used Vue.js, so I apologize if I've made some mad things :-)
I heavily use it from my phone and I've been frustrated by the footer, so here is a PR with a couple of modifications:
* seek bar thicker
* other-controls bigger (1.2rem)
It **hugely** improves the user experience on a small screen. What do you think?
Tested on Android 4.4 with Firefox and Chrome.
Signed-off-by: Daniele Ricci <daniele.athome@gmail.com>

Some mobile optimizations

---

resources/assets/js/components/shared/home-song-item.vue

Fixes  Issue https://github.com/phanan/koel/issues/387

Fixes Pause and Resume in home-song-item.

---

app/Application.php
app/Console/Commands/Init.php
app/Http/Controllers/API/DataController.php
app/Http/Controllers/API/SongController.php
app/Http/Requests/API/Download/Request.php
app/Http/Streamers/TranscodingStreamer.php
app/Services/Lastfm.php
app/Services/Media.php
app/Services/YouTube.php
config/jwt.php
config/koel.php
database/seeds/UserTableSeeder.php
tests/ApplicationTest.php

Please see https://github.com/phanan/koel/pull/409 for details.
Once this is merged I will create an additional PR for the UserTableSeeder changes.

Populate dotenv to config

---

resources/assets/js/components/main-wrapper/main-content/index.vue

I've got very long album titles on relatively small screen... And titles were all messed up !

Change line-height on headings

---

database/seeds/UserTableSeeder.php

Modified to strict comparison.

Clean UserTableSeeder

---

database/seeds/UserTableSeeder.php

Fixes https://github.com/phanan/koel/issues/432

Password hashing.

---

resources/assets/js/components/shared/song-item.vue

Resolves https://github.com/phanan/koel/issues/436.
I guess the merge is based on, if its a vue bug or not.

Remove v-once for time class

---

tests/TestCase.php

Fixes https://github.com/phanan/koel/issues/449

Fix img dir when running tests.

---

app/Services/Media.php
config/koel.php
tests/MediaTest.php

As per https://github.com/phanan/koel/issues/450#issuecomment-247864925

Fix spelling

---

resources/assets/js/app.vue

Tested and works on Firefox and Chrome

Fix scrollable issue with Firefox.

---

composer.json
composer.lock

Added predis to composer.json this will let koel use redis for it's session driver, cache driver, broadcast driver, and queue driver.

Added predis to composer.json

---

package.json

fixes for recent breaking changes made to the cross-env JavaScript dependency

cross-env fix

---

resources/assets/js/services/socket.js

convert static string to template string to use the variable

fix pusher auth endpoint path

---

composer.json
database/migrations/2016_04_16_082627_create_various_artists.php
database/migrations/2016_06_16_134516_cascade_delete_user.php
database/migrations/2017_04_29_025836_rename_contributing_artist_id.php

A recent change in Laravel 5.7 [totally breaks the tests](https://github.com/laravel/framework/issues/25475). This fixes the issue.

Fix broken tests due to Laravel change

---

app/Http/Controllers/API/DataController.php
app/Http/Controllers/API/Interaction/RecentlyPlayedController.php
app/Repositories/InteractionRepository.php
app/Services/InteractionService.php
routes/api.php

Add "Recently Played" playlist

---

app/Services/FileSynchronizer.php
composer.json
composer.lock
tests/Feature/MediaSyncTest.php

Downgrading getID3 to possibly fix #1078.

Downgrade getID3

---

.github/workflows/e2e.yml

Use the official GitHub action from Cypress to better access advanced build features.

feat(build): use official Cypress actions

---

app/Console/Commands/InitCommand.php

Two problems here:
1) endlessly attempting to reconnect (with no interval between attempts)
is a nightmare that will use resources and spam logs with no respite
2) attempting to update the database credentials on a connection failure
is definitely not the right thing to do, as they cannot be requested
when non-interactive.
Problem 1 is not really an issue in interactive use, because the user
being asked for credentials will slow down the connection attempts.
Problem 2 _could_ conceivably be a problem in interactive mode (if
there's some sort of transient connection failure), but if this is a
problem, it should perhaps be discussed & addressed separately.

fix: non-interactive database connection failures

---

database/migrations/2021_12_06_164648_increase_string_columns_length.php

feat: increase char limit for name fields

---

.github/workflows/e2e.yml
.github/workflows/release.yml

fix: broken release action

---

.github/workflows/release.yml

Resolve https://github.com/koel/koel/issues/1535 to reduce the release package size

feat(build): add no-dev option

---

.github/workflows/unit-backend-pgsql.yml
config/database.php
tests/Feature/DownloadTest.php
tests/Feature/SongTest.php

…to make sure we don't have PostgreSQL issues like #1537.

feat(build): add unit tests with PostgreSQL

---

resources/assets/js/components/ui/SearchForm.spec.ts
resources/assets/js/components/ui/SearchForm.vue

fix(search): broken redirection on mobile

---

package.json
resources/assets/js/__tests__/UnitTestCase.ts
resources/assets/js/app.ts
resources/assets/js/components/layout/app-footer/FooterExtraControls.vue
resources/assets/js/components/layout/app-footer/__snapshots__/FooterExtraControls.spec.ts.snap
resources/assets/js/components/layout/app-footer/__snapshots__/FooterPlaybackControls.spec.ts.snap
resources/assets/js/components/layout/main-wrapper/ExtraPanel.vue
resources/assets/js/components/playlist/smart-playlist/CreateSmartPlaylistForm.vue
resources/assets/js/components/playlist/smart-playlist/EditSmartPlaylistForm.vue
resources/assets/js/components/playlist/smart-playlist/SmartPlaylistRule.vue
resources/assets/js/components/song/SongListControls.vue
resources/assets/js/components/ui/ExtraPanelTabHeader.vue
resources/assets/js/components/ui/ProfileAvatar.vue
resources/assets/js/components/ui/RepeatModeSwitch.vue
resources/assets/js/components/ui/ViewModeSwitch.vue
resources/assets/js/components/ui/Volume.vue
resources/assets/js/components/ui/__snapshots__/ProfileAvatar.spec.ts.snap
resources/assets/js/directives/index.ts
resources/assets/js/directives/tooltip.ts
resources/assets/sass/app.scss
resources/assets/sass/partials/_tooltip.scss
yarn.lock

Add tooltips to some vague icon buttons for a better UX.

feat: add tooltips for better UX

---

resources/assets/sass/partials/_tooltip.scss

fix: broken layout on mobile due to tooltips (closes #1559)

---

resources/assets/js/__tests__/setup.ts
resources/assets/js/components/layout/ModalWrapper.spec.ts
resources/assets/js/components/layout/ModalWrapper.vue
resources/assets/js/components/meta/AboutKoelModal.vue
resources/assets/js/components/meta/__snapshots__/AboutKoelModal.spec.ts.snap
resources/assets/js/components/song/EditSongForm.vue
resources/assets/sass/partials/_shared.scss

Use HTML Dialog element for modals for better accessibility.

feat: use Dialog element for modals

---

resources/assets/js/utils/visualizer.ts

fix: volume increased when visualizer is activated

---

resources/assets/js/components/screens/PlaylistScreen.spec.ts
resources/assets/js/components/screens/PlaylistScreen.vue
resources/assets/js/components/screens/UploadScreen.vue
resources/assets/js/components/screens/__snapshots__/AllSongsScreen.spec.ts.snap
resources/assets/js/components/song/SongListControls.vue
resources/assets/js/components/ui/BtnGroup.vue
resources/assets/js/components/ui/ScreenHeader.vue
resources/assets/js/stores/songStore.spec.ts
resources/assets/js/stores/songStore.ts
resources/assets/js/symbols.ts
resources/assets/js/types.d.ts

Allow refreshing playlists, useful for e.g., smart playlists.

feat: allow refreshing playlists

---

app/Services/Streamers/PhpStreamer.php

fix: direct streaming with PHP not working for Safari

---

app/Repositories/SongRepository.php
resources/assets/js/components/song/SongListSorter.vue
resources/assets/js/types.d.ts

feat: allow sorting by date added

---

app/Http/Kernel.php
app/Http/Middleware/EncryptCookies.php
app/Http/Middleware/TrimStrings.php
app/Http/Middleware/VerifyCsrfToken.php
composer.lock

This fixes the E2E tests from Larastan. See [this fails job](https://github.com/nunomaduro/larastan/actions/runs/4195712248/jobs/7275643537).
The types needed to be added because after upgrading PHPStan / Larastan these errors where found.

chore(deps): update dependencies

---

resources/assets/js/components/ui/ProfileAvatar.vue

fix null value with checking the currentuser

fix: null currentUser on avatar (closes #1679)

---

config/filesystems.php
database/migrations/2024_01_03_104241_support_multi_tenant.php

fix: deperecation warning when trim() null values

---

app/Builders/SongBuilder.php

fix: broken pgsql query with distinct()

---

app/Builders/SongBuilder.php
app/Repositories/AlbumRepository.php
app/Repositories/ArtistRepository.php
app/Repositories/SongRepository.php
database/migrations/2024_07_14_180751_convert_json_columns_to_text.php

fix: issues with DISTINCT on pgsql

---

app/Models/Album.php
app/Models/Artist.php
app/Models/License.php
app/Models/Playlist.php
app/Models/PlaylistCollaborationToken.php
app/Models/Song.php
app/Models/User.php

Use `shouldCache()` on (applicable) attributes for some micro improvements.

chore: cache model attributes

---

app/Attributes/DisabledInDemo.php
app/Http/Controllers/API/ForgotPasswordController.php
app/Http/Controllers/API/Podcast/PodcastController.php
app/Http/Controllers/API/ProfileController.php
app/Http/Controllers/API/ResetPasswordController.php
app/Http/Controllers/Controller.php
app/Http/Kernel.php
app/Http/Middleware/HandleDemoMode.php
tests/Feature/ForgotPasswordTest.php
tests/Feature/ProfileTest.php

Use `#[DisabledInDemo]` to mark controller class/action that should be disabled in demo mode.

feat: use PHP attribute to mark requests disabled in demo

---

package-lock.json
package.json
resources/assets/js/config/visualizers.ts
resources/assets/js/visualizers/butterchurn/index.ts
yarn.lock

I don't tend to work with yarn or node so I'm not sure which  package files have necessary changes/which changes in those files are necessary. 
Closes #1891

feat: add Butterchurn visualizer

---

app/Console/Commands/ScanCommand.php
app/Enums/ScanEvent.php
app/Http/Controllers/API/FetchInitialDataController.php
app/Repositories/SettingRepository.php
app/Rules/SupportedAudioFile.php
app/Services/FileScanner.php
app/Services/MediaScanner.php
app/Services/Streamer/Streamer.php
app/Values/ScanResult.php
app/Values/SongScanInformation.php
config/koel.php
docs/usage/music-discovery.md
docs/usage/streaming.md
resources/assets/js/components/screens/UploadScreen.vue
resources/assets/js/composables/useUpload.ts
resources/assets/js/config/acceptedMediaTypes.ts
resources/assets/js/utils/mediaHelper.ts
tests/Integration/Services/MediaScannerTest.php

Adding AIFF as an experimental format. Also added some opportunistic improvements.

feat: support AIFF (closes #1913)

---

resources/assets/js/components/screens/PlaylistScreen.vue
resources/assets/js/components/song/song-list/SongListControls.vue
resources/assets/js/components/song/song-list/SongListFilter.spec.ts
resources/assets/js/components/song/song-list/SongListFilter.vue
resources/assets/js/composables/useSongList.ts
resources/assets/js/stores/songStore.spec.ts

feat: separate states between playlists

---

resources/assets/js/components/screens/PodcastListScreen.vue
resources/assets/js/components/screens/PodcastScreen.vue
resources/assets/js/components/song/song-list/SongListControls.vue
resources/assets/js/components/ui/ListFilter.spec.ts
resources/assets/js/components/ui/ListFilter.vue
resources/assets/js/composables/useSongList.ts
resources/assets/js/symbols.ts

…after the latest change to the `SongListFilter` (now renamed to just `ListFilter`) component.

fix: broken podcast filter

---

resources/assets/js/components/screens/GenreScreen.vue
resources/assets/js/components/ui/ThumbnailStack.vue
resources/assets/js/stores/songStore.ts

also avoiding re-rendering thumbnail stacks unnecessarily.

fix: genre screen not showing songs properly

---

app/Services/SongStorages/LocalStorage.php

fix: local deletion of song files

---

app/Builders/AlbumBuilder.php
app/Builders/ArtistBuilder.php
app/Builders/SongBuilder.php
app/Http/Resources/AlbumResource.php
app/Http/Resources/ArtistResource.php
app/Models/Song.php
app/Repositories/AlbumRepository.php
app/Repositories/ArtistRepository.php
app/Repositories/PodcastRepository.php
app/Repositories/SongRepository.php
app/Responses/SongUploadResponse.php
app/Values/UserPreferences.php
database/migrations/2025_06_12_150202_user-scope_artists_and_albums.php
docs/usage/profile-preferences.md
resources/assets/js/__tests__/factory/albumFactory.ts
resources/assets/js/__tests__/factory/artistFactory.ts
resources/assets/js/__tests__/factory/userFactory.ts
resources/assets/js/components/album/AlbumCard.spec.ts
resources/assets/js/components/album/AlbumCard.vue
resources/assets/js/components/album/__snapshots__/AlbumCard.spec.ts.snap
resources/assets/js/components/artist/ArtistCard.spec.ts
resources/assets/js/components/artist/ArtistCard.vue
resources/assets/js/components/artist/__snapshots__/ArtistCard.spec.ts.snap
resources/assets/js/components/profile-preferences/PreferencesForm.vue
resources/assets/js/components/screens/AllSongsScreen.spec.ts
resources/assets/js/components/screens/AllSongsScreen.vue
resources/assets/js/components/screens/__snapshots__/AllSongsScreen.spec.ts.snap
resources/assets/js/stores/preferenceStore.ts
resources/assets/js/types.d.ts

feat: option to include/exclude publicly shared media

---

composer.json
composer.lock

fix: downgrade sodium_compat to work with 32bit systems

---

app/Repositories/GenreRepository.php

fix: broken no-genre summary if all songs have genres

---

resources/assets/js/components/embed/widget/audio-player/EmbedAudioPlayer.vue
resources/assets/js/components/embed/widget/audio-player/EmbedAudioPlayerNextButton.vue
resources/assets/js/components/embed/widget/audio-player/EmbedAudioPlayerPlayButton.spec.ts
resources/assets/js/components/embed/widget/audio-player/EmbedAudioPlayerPlayButton.vue

- Lower volume gradually toward the end of the track
- Display a circular progress bar around the Play button

feat: improvements for embeds in preview mode
