koel/koel

- resources/assets/js/app.vue
- resources/assets/js/components/shared/song-list.vue
- resources/assets/js/services/utils.js
Prior to this PR being merged, the `orderBy` for columns is case sensitive. That means my list places lowercased-artist `mewithoutyou` after the entire list of Title-cased artists.
After the change:
Heavy caveat: the hacked functions that I stole from Vue core are not quite as good as the core versions, but I couldn't figure out how to import core Vue functions. Maybe it's possible?
> Add case insensitive order by for list views

- .gitignore
`node_modules` is already declared at the top of the file.
I would also like to ignore the `img` folder, what do you think about it?
> Remove .gitignore repeated declaration

- composer.json
Error will not be thrown when <code>composer install --no-dev</code> or <code>composer update --no-dev</code> command is used.
> Fixed composer install --no-dev issue

- app/Libraries/WatchRecord/InotifyWatchRecord.php
INotifyWait's CLOSE_WRITE and MOVED_TO events don't work on all operating systems. For those, the CREATE event looks like the best option.  
Fixes issue #247.
> Support INotifyWait CREATE event

- resources/assets/js/components/shared/song-item.vue
This adds some navigation links that I think are extremely useful for browsing a library without having to constantly go back to one of the main pages via the left-hand nav-bar. With this update, each song item can be used to navigate to its artist or album page.
> Added navigation links

- app/Models/Song.php
- app/Services/Media.php
- database/factories/ModelFactory.php
- database/migrations/2015_11_23_074713_create_songs_table.php
- resources/assets/js/app.vue
- resources/assets/js/components/modals/edit-songs-form.vue
- resources/assets/js/components/shared/song-list.vue
- tests/SongTest.php
This adds an optional `subSortKey` argument to the sort function so that we can perform a subsort on the data structure to allow for sorting by tracks when we sort by album.
This address issue https://github.com/phanan/koel/issues/240
> Sort by Track

- resources/views/index.blade.php
Added `theme-color` and `msapplication-navbutton-color`
`theme-color` supports Chrome, Firefox OS and Opera
`msapplication-navbutton-color` supports Windows Phone
> Add theme-color to index.blade.php

- app/Services/Media.php
By default, Koel does not follow symbolic links while scanning the music library (see issue #389). This is unfortunate for 2 reasons:
1. Koel does not allow adding multiple music library path (so it's not possible to have *per-user* music library), thus all users will see the same music library (and obviously, the most limited one).
2. It's possible to simulate the feature by adding symbolic links in the music library so it points to the user's folder (any users will see the music from all users), but without this patch, it does not work.
I'm not sure what should be the ideal solution for point 1, because if we have multiple path to to the music library, then it also means setting some kind of permission from cross-users access to the library and their personal library. At least with …
> Allow music library scanning to follow symbolic links 

- app/Models/File.php
Fix #412
Forgot to add this in the previous patch that allowed symbolic links
> Fix for cover albums not found

- app/Console/Commands/SyncMedia.php
- app/Models/File.php
- app/Services/Media.php
Currently, when the parser chokes on a file, it's counted as a "bad" file, and reported as so. 
Yet, we don't know the reason for the failure.
This patch implements this, it uncovers the failure reason from the parser, so the user could act accordingly to fix the issue.
Fix #405
> Allow failure reason to be reported in verbose mode 

- resources/assets/sass/partials/_shared.scss
I noticed that  in the settings page the em tag on the word absolute is not being rendered.
> Render html em tag

- phpunit.xml
When I was runing unit tests I was receiving HTTP error exceptions because there was no admin creds configured.
```php
1) ApplicationTest::testStaticUrlWithoutCDN
Symfony\Component\HttpKernel\Exception\HttpException:
C:\wamp64\www\koel\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:882
C:\wamp64\www\koel\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php:30
C:\wamp64\www\koel\database\seeds\UserTableSeeder.php:31
C:\wamp64\www\koel\database\seeds\UserTableSeeder.php:13
C:\wamp64\www\koel\vendor\laravel\framework\src\Illuminate\Database\Seeder.php:39
C:\wamp64\www\koel\database\seeds\DatabaseSeeder.php:16
C:\wamp64\www\koel\vendor\laravel\framework\src\Illuminate\Database\Console\Seeds\SeedCommand.php:63 …
```
> Add admin creds to unit testing

- resources/assets/js/components/main-wrapper/sidebar/index.vue
I noticed that when you browse to `/` we redirect to `/#!/home` but the sidebar returns `queue` as the `currentView`.
> Return 'home' view

- resources/assets/js/components/site-footer/equalizer.vue
If a preset was used in the previous session.
Now the application starts (before, it triggered an exception and failed to mount).
> Fix equalizer bug upon Koel starting 

- .travis.yml
* `--prefer-source` takes 117 seconds every builds.
* `--prefer-dist` takes only 13 seconds after cached.
> Use --prefer-dist to benefit from composer cache on travis

- app/Providers/AppServiceProvider.php
I know, the sqlite connection is not officially supported for production mode. But I have not limitations except for the on delete trigger. Perhaps you'd like to merge it anyway.
> enable foreign keys for sqlite connections

- resources/assets/js/components/auth/login-form.vue
- resources/assets/js/components/main-wrapper/extra/album-info.vue
- resources/assets/js/components/main-wrapper/main-content/album.vue
- resources/assets/js/components/main-wrapper/main-content/profile.vue
- resources/assets/js/components/main-wrapper/sidebar/index.vue
- resources/assets/js/components/main-wrapper/sidebar/playlist-item.vue
- resources/assets/js/components/shared/album-item.vue
- resources/assets/js/components/shared/artist-item.vue
- resources/assets/js/components/shared/home-song-item.vue
- resources/assets/js/components/shared/sound-bar.vue
- resources/assets/js/components/shared/track-list-item.vue
- resources/assets/js/components/site-footer/index.vue
- resources/assets/js/components/site-header/user-badge.vue
- resources/assets/js/router.js
- resources/assets/js/services/download.js
- resources/assets/js/services/http.js
- resources/assets/js/services/socket.js
- resources/assets/js/stores/song.js
- resources/views/client-js-vars.blade.php
- resources/views/index.blade.php
- resources/views/remote.blade.php
this is an improvement of #671 
All absolute paths were replaced with relative ones. The base url is set by Laravel in `client-js-vars.blade.php`. In API calls the base url is used instead of the root url.
With these changes it is possible to use the koel server also in a sub folder of a web server.
These changes are working fine. I hope this can be used so other people can use this functionality. #529
> add support for non root installations

- app/Console/Commands/Init.php
Just a small PR to fix this issue that prevents the koel:init assistant to configure a PostgreSQL driver correctly because of a small typo in `setUpDatabase()`. The value should be `pgsql` and not `pqsql`.
And thank you for koel, you do an amazing job :clap:
> Dabase driver typo for koel:init

- app/Http/Controllers/API/ObjectStorage/S3/SongController.php
I had 2 troubles when running Koel with [the official Koel-AWS package](https://github.com/koel/koel-aws)
1. MySQL Error: "Integrity constraint violation - Column 'lyrics' cannot be null" when AWS Lambda function request to Koel's Song API. (Environment: MySQL v5.5.47 & PHP v7.1)
Similar to [this issue](https://stackoverflow.com/questions/43860634/laravel-5-4-upgrade-integrity-constraint-violation-column-cannot-be-null). 
2. After storing a new songs, the song, album and artist didn't show up in Koel UI, because media cache remains.
> Fix AWS S3 related issues.

- app/Services/FileSynchronizer.php
`exif_imagetype()` can fail if the image is too small, breaking the whole scan. This fixes the issue.
> Fix error with cover file

- config/app.php
For the sake of testing, it is easier to have the key fit the required 32 character limit for AES-256-CBC. If the default 'SomeRandomString' placeholder is used, an invalid key length error is returned.
> Updated app.php default encryption key

- .env.example
- app/Console/Commands/InitCommand.php
- app/Repositories/AbstractRepository.php
- app/Repositories/SongRepository.php
- app/Services/MediaMetadataService.php
- app/Services/MediaSyncService.php
- config/koel.php
- tests/Integration/Repositories/SongRepositoryTest.php
As per https://github.com/phanan/koel/commit/e1b68cc53ff078429a968cb360ea250c1bc1b589#diff-ac5db72ed5e3c5612246e80cb231cacf (Dec 3, 2017), the admin account is NOT set in the `.env` file and created during initial database seeding anymore, therefore it's required to run:
$ php artisan koel:init
In **interactive mode** to configure koel, such process can be automatized with [expect](https://github.com/binhex/arch-koel/blob/938e4ce2646c180b5ea069f589487be2675eb24f/config/nobody/koel/init.exp) but IMHO it could be better if it uses environment variables when available.
This PR re enable:
- ADMIN_EMAIL=admin@example.com
- ADMIN_NAME=admin
- ADMIN_PASSWORD=admin
And add:
- APP_MEDIA_PATH=/music
To be able to run `$ php artisan koel:init` in **non interactive mode**
> Non interactive koel:init

- .env.example
- .gitignore
- app/Traits/SupportsDeleteWhereIDsNotIn.php
- config/database.php
All the tests already seem to run on sqlite, so there (in my mind) is no reason to not provide support for it.
The only change needed was to lower the delete chunk size.
> Add sqlite support

- .gitpod.dockerfile
- .gitpod.yml
- README.md
Hi There! hi @phanan!
I wanted to try koel but setting up may dev environment took painfully long. All that tinkering...
So I thought we can make that easier for everybody by having an online IDE ([gitpod.io](https://www.gitpod.io))) where everything is already configured, so that one can start running and hacking koel with just one click. 
If you click on the following link....
https://gitpod.io/#https://github.com/meysholdt/koel
1. a new docker-based workspace will launch. It's built from the `Dockerfile` in this PR
2. A `git clone` will fetch the koel source code. You may need to GitHub-OAuth-Login here.
3. the `.env.example` script is copied to `.env`
4. int the workspace, MySQL is started and a user+database based on the `.env` is created.
5. `php artisan koel:init` runs to let the …
> Make it easier to contribute to koel by having an online IDE

- app/Repositories/InteractionRepository.php
- app/Services/DownloadService.php
The column name is `liked` instead of `like` and there was a different `Collection` class being passed to the function. Fixes #746 (for me at least).
> Fix downloading songs from favourites playlist

- composer.json
This PR updates getID3 to use the latest 2.0 branch instead of the `v2.0.0-beta1` release which contains a fatal error when syncing.
The branch name came from:
https://github.com/JamesHeinrich/getID3/tree/2.0#installation
Fixes #1078
> Use the 2.0 branch of getID3

- app/Services/Streamers/TranscodingStreamer.php
Passing the glue parameter after the pieces parameter when calling
implode is deprecated as of PHP 7.4.
This was the only remaining instance, all other implode calls already
use the correct parameter order.
> Fix TranscodingStreamer for PHP 7.4

- .gitpod.yml
This PR adds vetur as an extension in Gitpod's VS code
"Vetur provides syntax highlighting, snippets, Emmet support, linting/error checking, auto-formatting, and auto-complete for Vue files."
Atm the vue files look like this on Gitpod:
After this change:
> Vue highlighting added for Gitpod

- .github/workflows/release.yml
- app/Console/Commands/InitCommand.php
This adds a build step on pushed tags that will install all dependencies and run the assets build step, zip/tar up the result and create a release draft. That draft can then have the release notes added and published which will then contain zip/tar versions that are ready to use.
It also adds a option to the init command to not build the assets, which removes the install dependency on yarn/node.
The zip/tar files come with sqlite configured as the default db, mostly because that is the only one without runtime dependencies.
The point of this is to enable people to get going with koel without git/composer/node/yarn, so that a basic install can be run with only php as
curl -LO https://github.com/SahAssar/koel/releases/download/v0.0.7-beta3/koel-v0.0.7-beta2.zip
unzip koel-v0.0.7-beta2.zip …
> Build via github actions

- config/database.php
I happen to use a central instance of Redis for various projects and could use having this change integrated, allowing to specify from .env the database to use.
> Add support for selecting Redis DB

- app/Http/Requests/API/UploadRequest.php
Before this change, Koel only recognized the non-standard MIME type audio/x-flac.
Server-side portion of https://github.com/koel/core/pull/53.
>  Recognize the standard MIME type for uploaded FLAC audio

- app/Http/Controllers/API/ObjectStorage/S3/SongController.php
The S3 song controller was setting `compilation` to true as long as an album artist was specified, even if it matched the artist tag. This PR adjusts the behavior to match the `isCompilation` method defined here: https://github.com/koel/koel/blob/aedff9cf6e055fa7f58eb08e52206ea750f33be2/app/Services/FileSynchronizer.php#L338-L345
> Fix S3 storage song compilation setting

- tests/Feature/LastfmTest.php
- tests/Feature/ObjectStorage/S3Test.php
- tests/Feature/SettingTest.php
- tests/Feature/SongTest.php
- tests/Feature/V6/PlayCountTest.php
- tests/Integration/Models/SongZipArchiveTest.php
- tests/Integration/Services/ApplicationInformationServiceTest.php
- tests/Integration/Services/InteractionServiceTest.php
- tests/Integration/Services/MediaSyncServiceTest.php
- tests/Unit/ApplicationTest.php
- tests/Unit/Models/AlbumTest.php
- tests/Unit/Models/SettingTest.php
- tests/Unit/Models/SongTest.php
- tests/Unit/Services/ApiClients/ApiClientTest.php
- tests/Unit/Services/ApiClients/LastfmClientTest.php
- tests/Unit/Services/MediaMetadataServiceTest.php
- tests/Unit/Services/YouTubeServiceTest.php
- It should use the `assertSame` to make assert equals strict.
> chore: improve assertEquals

- resources/assets/js/App.vue
- resources/assets/js/components/album/AlbumTrackListItem.vue
Lazyloading GlobalEventListeners may cause `LOG_OUT` event to not be listened to and handled properly.
> fix: do not lazy-load GlobalEventListeners

- .env.example
This port number actually determines how `yarn dev` displays and behaves:
```bash
$ yarn dev
4:35:34 PM [vite] server restarted.
➜  Local:   http://127.0.0.1:5173/
➜  Network: use --host to expose
LARAVEL v9.22.1  plugin v0.6.1
➜  APP_URL: http://localhost:8000 <--- THIS
```
> chore: add port 8000 into .env's APP_URL

- resources/assets/js/components/album/AlbumTrackListItem.spec.ts
Broken due to the change in injection at 2e34016b5749238d514050e93537775187b24ffc.
> fix: album tracklist item test

- app/Services/TranscodingService.php
- config/koel.php
It seems there were some attempts at making this work before but apparently they weren't done the right way or something.
The following request was closed as stale: https://github.com/koel/koel/pull/527
The following request was denied due to confusing label and wrong approach (?) https://github.com/koel/koel/pull/699
---
The only changes are: new config variable `koel.streaming.transcode_flac` that pulls data from `TRANSCODE_FLAC` env var and defaults to `true` in `config/koel.php` file and extended bool check in `app/Services/TranscodingService.php` file. [Full diff here.](https://github.com/koel/koel/compare/master...MaciejGorczyca:master#diff-c394adf35324659049bb91f7b82378371d236078ffeb27da855a076867d13f5e) 
The default behavior is the same as before but now you can turn off …
> feat: Add env TRANSCODE_FLAC (default true) to toggle transcoding on/off for FLAC files

- resources/assets/js/components/utils/HotkeyListener.vue
Since we're using the Space key to toggle playback, the default browser behavior (scroll to the next page) should be prevented.
> fix: pressing Space causes lists to scroll

- api-docs/api.yaml
- app/Models/Interaction.php
- app/Repositories/InteractionRepository.php
- app/Repositories/SongRepository.php
- app/Services/InteractionService.php
- app/Services/SmartPlaylistService.php
- app/Values/SmartPlaylistRule.php
- app/Values/SmartPlaylistSqlElements.php
- database/migrations/2022_11_08_144634_add_last_played_at_into_interactions_table.php
- resources/assets/js/components/ui/ScreenHeader.vue
- resources/assets/js/config/smart-playlist/models.ts
- resources/assets/js/types.d.ts
Add and use a `interactions.last_played_at` timestamp instead of relying on `interactions.updated_at`, which has always been buggy, as the latter is modified upon (un)marking songs as favorite as well.
Also in this PR:
> feat: add and use "last played" timestamp for songs

- app/Http/Controllers/API/AuthController.php
- app/Http/Controllers/API/ProfileController.php
- app/Http/Kernel.php
- app/Http/Middleware/AudioAuthenticate.php
- app/Http/Middleware/Authenticate.php
- app/Models/User.php
- app/Providers/AuthServiceProvider.php
- app/Services/TokenManager.php
- app/Values/CompositionToken.php
- resources/assets/js/App.vue
- resources/assets/js/components/album/AlbumTrackListItem.vue
- resources/assets/js/components/profile-preferences/LastfmIntegration.vue
- resources/assets/js/remote/App.vue
- resources/assets/js/services/authService.spec.ts
- resources/assets/js/services/authService.ts
- resources/assets/js/services/downloadService.ts
- resources/assets/js/services/http.ts
- resources/assets/js/services/socketService.ts
- resources/assets/js/stores/songStore.spec.ts
- resources/assets/js/stores/songStore.ts
- routes/web.base.php
- tests/Feature/AuthTest.php
- tests/Feature/DownloadTest.php
- tests/Integration/Services/TokenManagerTest.php
Use a composition token (API + web audio tokens) to prevent the API token from being logged by server and proxy software.
> feat: use a composition token

- app/Services/SongService.php
- app/Values/SongUpdateData.php
- tests/Feature/SongTest.php
Fixing a bug where updating multiple songs will leak data from the first song to the next.
Also fixing a bug where user can't clear some values when editing only one song.
> fix: update multiple songs duplicate values

- tests/Traits/CreatesApplication.php
See https://github.com/nunomaduro/larastan/pull/1451#issuecomment-1345599444
> fix: Added CreatesApplication strict typing

- resources/assets/js/components/screens/AlbumScreen.vue
- resources/assets/js/components/screens/ArtistScreen.vue
- resources/assets/js/components/screens/FavoritesScreen.vue
- resources/assets/js/components/screens/PlaylistScreen.vue
- resources/assets/js/components/screens/QueueScreen.vue
- resources/assets/js/components/screens/RecentlyPlayedScreen.vue
- resources/assets/js/components/screens/__snapshots__/AllSongsScreen.spec.ts.snap
- resources/assets/js/components/screens/search/SearchSongResultsScreen.vue
- resources/assets/js/components/song/SongList.vue
- resources/assets/js/components/song/SongListControls.vue
- resources/assets/js/components/song/SongListFilter.spec.ts
- resources/assets/js/components/song/SongListFilter.vue
- resources/assets/js/components/ui/ArtistAlbumScreenTabs.vue
- resources/assets/js/components/ui/Btn.vue
- resources/assets/js/composables/useSongList.ts
- resources/assets/js/composables/useSongListControls.ts
- resources/assets/js/symbols.ts
- resources/assets/js/types.d.ts
Adding the feature of filtering simple song lists (Queue, Favorites, Playlist…). Lists that can be server-paginated (All Songs and Genre) are not applicable at the moment due to the extra complexity.
> feat: allow filtering (applicable) song lists

- nginx.conf.example
This PR specifies a `send_timeout` in the example `nginx` configuration.
If the `koel` client has not finished buffering a song within the default client timeout (60s), `nginx` closes the connection. This causes the song to either stop playing in a desktop browser, or skip to the beginning and endlessly repeat in the mobile app. By increasing the client timeout, `nginx` keeps the connection open until buffering is done.
c.f. https://www.davidschlachter.com/misc/koel-songs-skipping-stopping
> feat: increase send_timeout in nginx config

- resources/assets/sass/partials/_shared.scss
This has been verified working on Chrome, Firefox and Safari on MacOS Ventura and can close #1639 on merge.
> feat: use dark color scheme

- app/Repositories/SongRepository.php
The track ordering on multiple disc albums should first order by the actual disc and then by the track number. Previously it was first sorted by the track, causing you to hear the first track of every disc and then going to the second track of every disk.
Fixes #1089
> Fix the track ordering on multi disc albums

- app/Helpers.php
- resources/views/base.blade.php
I've encountered an issue when running behind a reverse proxy. Proxy terminates SSL correctly and provides correct `X-Forwarded` headers, but URLs generated for the frontend aren't `https`, so it tries to call the API via `http` which browsers explicitly forbid and throw an error along the lines of `...was not allowed to display insecure content from http://...`
This PR fixes the `BASE_URL` explicitly used in Vue and the URL in `<base>` tag which may be used implicitly.
Now the "non-working" `APP_URL` ENV value actually does something.
> fix(frontend): Fix the base URL supplied to the frontend

- app/Http/Controllers/API/DataController.php
- resources/assets/js/components/album/AlbumInfo.vue
- resources/assets/js/components/artist/ArtistInfo.vue
- resources/assets/js/components/profile-preferences/LastfmIntegration.vue
- resources/assets/js/components/profile-preferences/SpotifyIntegration.spec.ts
- resources/assets/js/components/profile-preferences/SpotifyIntegration.vue
- resources/assets/js/components/profile-preferences/__snapshots__/SpotifyIntegration.spec.ts.snap
- resources/assets/js/components/screens/ProfileScreen.vue
- resources/assets/js/composables/useThirdPartyServices.ts
This fixes a bug with Spotify integration that occurs if an installation isn't connected to Last.fm. Closing #1730 and #1653.
> fix: buggy Spotify integration

- .env.example
- app/Http/Middleware/TrustHosts.php
- config/app.php
After commit https://github.com/koel/koel/commit/e969549, Koel accepts only the hostname from `APP_URL` (and all its sub domains) as trusted hosts, as long as HTTPS is not enforced. This breaks access with `.env.example`, until `APP_URL` is set, and then allows to define a single trusted host only, which can be a problem instances which one wants to access from localhost, from within LAN via local hostname or IP, and remotely with a public hostname at the same time, or for testing instances.
This commit introduces a new config key `TRUSTED_HOSTS`. It is empty by default, which permits access via all hostnames, restoring the pre-v7.0.0 behaviour. When definitng it as comma-separated list of hostnames (and/or IPs), access is restricted to those.
Fixes: #1796
> feat: implement and use new confg key for trusted hosts

- app/Console/Commands/InitCommand.php
- docs/cli-commands.md
In the Cloudron package, we have a readonly filesystem and the cron is run outside the container . This option allows skipping installation of the scheduler crontab.
> feat: add option to skip installation of scheduler

- resources/assets/js/components/layout/app-footer/FooterSongInfo.vue
- resources/assets/js/components/ui/__snapshots__/ProfileAvatar.spec.ts.snap
- resources/assets/js/components/user/UserAvatar.vue
- display defaultCover when processing empty cover image
- load default avatar when avatar loading fails, because the network in some places can't access www.gravatar.com, I added the default avatar to use logo.
@phanan TBR; thank you for your excellent work to bring us joy, If there is anything I can do for you, please let me know.
**[Surprise Origin] [lzc-app](https://lazycat.cloud/appstore/%2Fshop%2Fdetail%2Fcloud.lazycat.app.koel) porting upstream code giveback plan**
> fix: display defaultCover when processing empty cover image

- .github/workflows/unit-backend-mysql.yml
- .github/workflows/unit-backend-pgsql.yml
- .github/workflows/unit-backend.yml
Upgrading `actions/upload-artifact` to v4 as GitHub dropped support for v1 and v2.
> feat(build): upgrade actions/upload-artifact to v4

- .github/workflows/release.yml
GitHub has deprecated both `create-release` and `upload-release-asset` actions. This PR replace them with the actively-maintained (and suggested by GitHub) `softprops/action-gh-release`.
> feat(build): use action-gh-release instead of deprecated GH actions for release

- config/koel.php
Currently if `STORAGE_DRIVER` is set to an empty string in `.env`, `config('koel.storage_driver')` will return an empty string instead of `'local'` and break some functionalities.
> fix: ensure default storage is local

- resources/assets/js/__tests__/UnitTestCase.ts
- resources/assets/js/__tests__/factory/podcastFactory.ts
- resources/assets/js/components/screens/PlaylistScreen.vue
- resources/assets/js/components/song/song-list/SongList.spec.ts
- resources/assets/js/components/song/song-list/SongList.vue
- resources/assets/js/components/song/song-list/SongListControls.spec.ts
- resources/assets/js/components/song/song-list/SongListControls.vue
- resources/assets/js/composables/useSongList.ts
- resources/assets/js/symbols.ts
Song controls disappear if the filter returns an empty result set, since we are relying on the number of songs returned. Fixing by relying on the number of original songs before filtering instead.
> fix: song controls disappear during filtering

- resources/assets/js/components/song/song-list/SongListHeader.spec.ts
- resources/assets/js/components/song/song-list/SongListHeader.vue
- resources/assets/js/components/song/song-list/SongListHeaderActionMenu.spec.ts
- resources/assets/js/components/song/song-list/SongListHeaderActionMenu.vue
- resources/assets/js/components/song/song-list/__snapshots__/SongListHeader.spec.ts.snap
Now that the "SongListSorter" has expanded its functionality to both a sorter and a column picker, it should be renamed accordingly and always shown.
> feat: always show song list header action menu

- database/migrations/2025_07_04_090408_denormalize_artist_albums.php
Apparently for large text columns, the text index supporting all databases is fullText() https://laravel.com/docs/12.x/migrations#available-index-types
Fixes #2010
> Use fullText() index for artist and album name columns

- resources/assets/js/components/album/AlbumInfo.vue
There were circumstances where an album/track wouldn't have a link available but the 'Source' text would still be present.
> fix: empty URL would sometimes be displayed

- app/Helpers.php
- app/Models/Album.php
- app/Models/Artist.php
- app/Models/Playlist.php
- app/Models/RadioStation.php
- app/Observers/AlbumObserver.php
- app/Observers/ArtistObserver.php
- app/Observers/PlaylistObserver.php
- app/Observers/RadioStationObserver.php
- app/Services/ArtworkService.php
- app/Services/UserService.php
- config/koel.php
- public/.gitignore
- tests/Feature/AlbumCoverTest.php
- tests/Feature/AlbumTest.php
- tests/Feature/ArtistImageTest.php
- tests/Feature/ArtistTest.php
- tests/Feature/ProfileTest.php
- tests/Integration/Services/AlbumServiceTest.php
- tests/Integration/Services/ArtistServiceTest.php
- tests/Integration/Services/EncyclopediaServiceTest.php
- tests/Integration/Services/UserServiceTest.php
- tests/TestCase.php
- tests/Unit/Services/ArtworkServiceTest.php
Moving all generated/uploaded images (album arts, artist images, etc.) to under one `public/img/storage` folder.
> feat: unify all generated/uploaded images

- .env.example
- composer.json
- docs/cli-commands.md
- docs/guide/getting-started.md
- scripts/koel-init.php
Add a composer script to execute `php artisan koel:init` only after resolving all PHP dependencies.
> feat: add composer script for koel:init

- app/Http/Integrations/Wikidata/WikidataConnector.php
- app/Http/Integrations/Wikipedia/WikipediaConnector.php
- app/Pipelines/Encyclopedia/GetAlbumTracksUsingMbid.php
- app/Pipelines/Encyclopedia/GetAlbumWikidataIdUsingReleaseGroupMbid.php
- app/Pipelines/Encyclopedia/GetArtistWikidataIdUsingMbid.php
- app/Pipelines/Encyclopedia/GetMbidForArtist.php
- app/Pipelines/Encyclopedia/GetReleaseAndReleaseGroupMbidsForAlbum.php
- app/Pipelines/Encyclopedia/GetWikipediaPageSummaryUsingPageTitle.php
- app/Pipelines/Encyclopedia/GetWikipediaPageTitleUsingWikidataId.php
- app/Pipelines/Encyclopedia/RemembersForever.php
- app/Services/ImageWriter.php
Fixes two things:
- Broken Wikipedia/Wikimedia connector due to a recent [policy enforcement](https://phabricator.wikimedia.org/T400119).
- Broken image writing with Intervention not automatically fetching the image source from a remote URL anymore.
Closes #2129
> fix: wikipedia connector and imagewriter got broken
